Edited file for class
IT3049C/students pull request #228
Opened 2022-01-16 16:53 UTC by dumforjh

2022-01-16 16:53 UTC, dumforjh commented
Did this for class

2022-01-17 05:19 UTC, Ygilany requested changes
You had this typo here

2022-01-17 05:19 UTC, Ygilany commented on _data/semesters/Spring 22/dumforjh.json
> +          "twitter": site: "https://twitter.com/john_dumford",
```suggestion
          "site": "https://it3049c-students.github.io/1-online-portfolio-dumforjh/",
          "linkedin":"https://www.linkedin.com/in/john-dumford-27a108201/",
          "facebook": "https://www.facebook.com/profile.php?id=100012598806765",
          "twitter": "https://twitter.com/john_dumford"
```

2022-01-17 05:22 UTC, Ygilany commented
Please fill out the self-evaluation and make sure the assignment pass the automated checks

2023-02-03 18:55 UTC, closed without merging